export const whistleblowerApplications = [
  {
    id: 1,
    name: "Chiamaka Okonkwo",
    email: "chiamaka@email.com",
    phone: "+234 812 345 6789",
    address: "Block 5, Flat 2A, Yaba, Lagos",
    linkedin: "https://linkedin.com/in/chiamaka-okonkwo",
    facebook: "https://facebook.com/chiamaka.okonkwo",
    instagram: "https://instagram.com/chiamaka_ok",
    status: "pending",
    appliedDate: "Dec 20, 2024",
    redFlags: ["New Instagram account (created 3 months ago)"],
    greenFlags: [
      "Real LinkedIn profile with job history at tech company",
      "Facebook account with real friends and location check-ins in Yaba",
      "Job title matches profile bio",
    ],
    socialScore: 78,
  },
  {
    id: 2,
    name: "John Property Consultant",
    email: "john@realestate.com",
    phone: "+234 801 234 5678",
    address: "Block 3, Flat 1C, Yaba, Lagos",
    linkedin: "https://linkedin.com/in/john-realtor",
    facebook: "https://facebook.com/johnproperty",
    instagram: "https://instagram.com/johnproperties",
    status: "rejected",
    appliedDate: "Dec 18, 2024",
    redFlags: [
      'Instagram bio explicitly says "Properties for rent - DM me"',
      "Posts 20+ properties per week on Instagram",
      "Instagram account created 2 weeks ago",
      "Email domain is real estate company",
      "This is their 5th application this month",
      "Location posts show properties in multiple cities",
    ],
    greenFlags: [],
    socialScore: 8,
  },
  {
    id: 3,
    name: "Adanna Smith",
    email: "adanna@email.com",
    phone: "+234 803 456 7890",
    address: "Block 2, Flat 4D, Yaba, Lagos",
    linkedin: "https://linkedin.com/in/adanna-smith",
    facebook: "https://facebook.com/adanna.smith",
    instagram: "https://instagram.com/adanna_smith",
    status: "approved",
    appliedDate: "Dec 15, 2024",
    approvedDate: "Dec 16, 2024",
    redFlags: [],
    greenFlags: [
      "Strong LinkedIn profile with 5+ year work history",
      "Real job at established company",
      "Facebook shows real social life with friends",
      "Instagram has regular personal posts (not property focused)",
      "All location tags match Yaba address",
    ],
    socialScore: 92,
  },
] as const
