export const allProperties = [
  {
    id: 1,
    title: "Modern 3 Bedroom Flat",
    location: "Lekki Phase 1, Lagos",
    price: 3500000,
    beds: 3,
    baths: 3,
    sqm: 150,
    image: "/properties/lekki-flat.jpg",
    tag: "POPULAR",
    tagColor: "bg-primary",
    whistleblower: { name: "Chiamaka Okonkwo", rating: 4.8, reviews: 24 },
  },
  {
    id: 2,
    title: "Spacious 2 Bedroom Apartment",
    location: "Wuse 2, Abuja",
    price: 2800000,
    beds: 2,
    baths: 2,
    sqm: 120,
    image: "/properties/wuse-apt.jpg",
    tag: "NEW",
    tagColor: "bg-secondary",
    whistleblower: { name: "Adanna Smith", rating: 4.9, reviews: 18 },
  },
  {
    id: 3,
    title: "Luxury 4 Bedroom Duplex",
    location: "Ikoyi, Lagos",
    price: 8500000,
    beds: 4,
    baths: 4,
    sqm: 300,
    image: "/properties/ikoyi-duplex.jpg",
    tag: "PREMIUM",
    tagColor: "bg-accent",
    whistleblower: { name: "Chioma Ukaegbu", rating: 4.7, reviews: 31 },
  },
  {
    id: 4,
    title: "Cozy Studio Apartment",
    location: "Yaba, Lagos",
    price: 1200000,
    beds: 1,
    baths: 1,
    sqm: 45,
    image: "/properties/yaba-studio.jpg",
    tag: null,
    tagColor: null,
    whistleblower: { name: "Blessing Okafor", rating: 4.5, reviews: 12 },
  },
  {
    id: 5,
    title: "Executive 3 Bedroom Flat",
    location: "Victoria Island, Lagos",
    price: 5500000,
    beds: 3,
    baths: 3,
    sqm: 180,
    image: "/properties/vi-flat.jpg",
    tag: "HOT",
    tagColor: "bg-destructive",
    whistleblower: { name: "Tunde Adeyemi", rating: 4.6, reviews: 19 },
  },
  {
    id: 6,
    title: "Family 4 Bedroom Bungalow",
    location: "Gwarimpa, Abuja",
    price: 4200000,
    beds: 4,
    baths: 3,
    sqm: 220,
    image: "/properties/gwarimpa-bungalow.jpg",
    tag: null,
    tagColor: null,
    whistleblower: { name: "Folake Adekunle", rating: 4.4, reviews: 8 },
  },
  {
    id: 7,
    title: "Modern 2 Bedroom Flat",
    location: "Ikeja GRA, Lagos",
    price: 2400000,
    beds: 2,
    baths: 2,
    sqm: 100,
    image: "/properties/ikeja-flat.jpg",
    tag: "NEW",
    tagColor: "bg-secondary",
    whistleblower: { name: "Zainab Hassan", rating: 4.9, reviews: 27 },
  },
  {
    id: 8,
    title: "Penthouse Suite",
    location: "Banana Island, Lagos",
    price: 15000000,
    beds: 5,
    baths: 5,
    sqm: 400,
    image: "/properties/banana-penthouse.jpg",
    tag: "LUXURY",
    tagColor: "bg-accent",
  },
];

export const propertyFilters = {
  locations: ["All Locations", "Lagos", "Abuja", "Port Harcourt"],
  priceRanges: [
    "Any Price",
    "Under ₦2M",
    "₦2M - ₦5M",
    "₦5M - ₦10M",
    "Above ₦10M",
  ],
  bedOptions: ["Any", "1", "2", "3", "4+"],
};
